import { colorList } from '@/enums/theme'

export default {
  version: 1,
  themeName: 'lightEChartsTheme',
  theme: {
    seriesCnt: '1',
    backgroundColor: 'rgba(0,0,0,0)',
    titleColor: '#0052D9',
    subtitleColor: '#aaaaaa',
    textColorShow: false,
    textColor: '#333',
    markTextColor: '#ffffff',
    color: colorList,
    borderColor: '#cccccc',
    borderWidth: '0',
    visualMapColor: ['#c1232b', '#fcce10'],
    legendTextColor: '#475569',
    kColor: '#c1232b',
    kColor0: '#b5c334',
    kBorderColor: '#c1232b',
    kBorderColor0: '#b5c334',
    kBorderWidth: 1,
    lineWidth: '2',
    symbolSize: '1',
    symbol: 'emptyCircle',
    symbolBorderWidth: '2',
    lineSmooth: true,
    graphLineWidth: 1,
    graphLineColor: '#aaaaaa',
    mapLabelColor: '#c1232b',
    mapLabelColorE: 'rgb(100,0,0)',
    mapBorderColor: '#eeeeee',
    mapBorderColorE: '#444',
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: '#dddddd',
    mapAreaColorE: '#fe994e',
    axes: [
      {
        type: 'all',
        name: '通用坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)']
      },
      {
        type: 'category',
        name: '类目坐标轴',
        axisLineShow: true,
        axisLineColor: '#0052D9',
        axisTickShow: true,
        axisTickColor: '#27727b',
        axisLabelShow: true,
        axisLabelColor: '#94a3b8',
        splitLineShow: false,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)']
      },
      {
        type: 'value',
        name: '数值坐标轴',
        axisLineShow: false,
        axisLineColor: '#333',
        axisTickShow: false,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#94a3b8',
        splitLineShow: false,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)']
      },
      {
        type: 'log',
        name: '对数坐标轴',
        axisLineShow: true,
        axisLineColor: '#27727b',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)']
      },
      {
        type: 'time',
        name: '时间坐标轴',
        axisLineShow: true,
        axisLineColor: '#27727b',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.3)', 'rgba(200,200,200,0.3)']
      }
    ],
    axisSeperateSetting: true,
    toolboxColor: '#c1232b',
    toolboxEmphasisColor: '#e87c25',
    tooltipAxisColor: '#0052D9',
    tooltipAxisWidth: 1,
    timelineLineColor: '#293c55',
    timelineLineWidth: 1,
    timelineItemColor: '#27727b',
    timelineItemColorE: '#72d4e0',
    timelineCheckColor: '#c1232b',
    timelineCheckBorderColor: '#c23531',
    timelineItemBorderWidth: 1,
    timelineControlColor: '#27727b',
    timelineControlBorderColor: '#27727b',
    timelineControlBorderWidth: 0.5,
    timelineLabelColor: '#293c55',
    datazoomBackgroundColor: 'rgba(0,0,0,0)',
    datazoomDataColor: 'rgba(181,195,52,0.3)',
    datazoomFillColor: 'rgba(181,195,52,0.2)',
    datazoomHandleColor: '#27727b',
    datazoomHandleWidth: '100',
    datazoomLabelColor: '#999999'
  }
}
